<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\FormField;

class CreateFormFieldsTable extends Migration
{
    public function up()
    {
        Schema::create('form_fields', function (Blueprint $table) {
            $table->id();
            $table->string('form_type');
            $table->string('section');
            $table->string('name');
            $table->string('label');
            $table->string('type');
            $table->string('excel_cell');
            $table->text('tooltip');
            $table->string('validation')->nullable();
            $table->integer('order');
            $table->string('placeholder')->nullable();
            $table->timestamps();
        });

        // Seed the form fields
        $this->seedFormFields();
    }

    public function down()
    {
        Schema::dropIfExists('form_fields');
    }

    private function seedFormFields()
    {
        $fields = [
            [
                'form_type' => 'lenta',
                'name' => 'outerLength',
                'label' => 'Длина ленты внешней (п.м)',
                'type' => 'number',
                'excel_cell' => 'D4',
                'tooltip' => 'Общая длина внешнего периметра фундамента',
                'validation' => 'required|numeric|min:0',
                'order' => 1,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'outerWidth',
                'label' => 'Ширина ленты внешней (мм)',
                'type' => 'number',
                'excel_cell' => 'D5',
                'tooltip' => 'Ширина внешней ленты фундамента',
                'validation' => 'required|numeric|min:0',
                'order' => 2,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'innerLength',
                'label' => 'Длина ленты внутренней (п.м)',
                'type' => 'number',
                'excel_cell' => 'D6',
                'tooltip' => 'Общая длина внутренних перегородок фундамента',
                'validation' => 'required|numeric|min:0',
                'order' => 3,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'innerWidth',
                'label' => 'Ширина ленты внутренней (мм)',
                'type' => 'number',
                'excel_cell' => 'D7',
                'tooltip' => 'Ширина внутренних лент фундамента',
                'validation' => 'required|numeric|min:0',
                'order' => 4,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'plinthHeight',
                'label' => 'Высота цоколя (мм)',
                'type' => 'number',
                'excel_cell' => 'D8',
                'tooltip' => 'Высота цокольной части фундамента',
                'validation' => 'required|numeric|min:0',
                'order' => 5,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'crossIntersections',
                'label' => 'Количество пересечений крест (шт)',
                'type' => 'number',
                'excel_cell' => 'D9',
                'tooltip' => 'Количество мест, где ленты пересекаются крестообразно',
                'validation' => 'required|integer|min:0',
                'order' => 6,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'tIntersections',
                'label' => 'Количество пересечений Т-обр (шт)',
                'type' => 'number',
                'excel_cell' => 'D10',
                'tooltip' => 'Количество Т-образных соединений лент',
                'validation' => 'required|integer|min:0',
                'order' => 7,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'cornerCount',
                'label' => 'Количество углов Г (шт)',
                'type' => 'number',
                'excel_cell' => 'D11',
                'tooltip' => 'Количество прямых углов в фундаменте',
                'validation' => 'required|integer|min:0',
                'order' => 8,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'cornerCount45',
                'label' => 'Количество углов 45 гр (шт)',
                'type' => 'number',
                'excel_cell' => 'D12',
                'tooltip' => 'Количество углов 45 градусов в фундаменте',
                'validation' => 'required|integer|min:0',
                'order' => 9,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'buildingAreaOverlap',
                'label' => 'Перепад по пятну застройки (мм)',
                'type' => 'number',
                'excel_cell' => 'D13',
                'tooltip' => 'Перепад по пятну застройки',
                'validation' => 'required|numeric|min:0',
                'order' => 10,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'sandBaseThickness',
                'label' => 'Толщина песчаного основания (мм)',
                'type' => 'number',
                'excel_cell' => 'D14',
                'tooltip' => 'Толщина песчаного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 11,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'crushedStoneBaseThickness',
                'label' => 'Толщина щебеночного основания (мм)',
                'type' => 'number',
                'excel_cell' => 'D15',
                'tooltip' => 'Толщина щебеночного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 12,
            ],
            [
                'form_type' => 'lenta',
                'name' => 'buildingAreaSize',
                'label' => 'S пятна застройки (м2)',
                'type' => 'number',
                'excel_cell' => 'D16',
                'tooltip' => 'Площадь пятна застройки',
                'validation' => 'required|numeric|min:0',
                'order' => 13,
            ],
            [
                'form_type' => 'lp',
                'name' => 'horizontalWaterproofing',
                'label' => 'Горизонтальная гидроизоляция плиты перекрытия НЕТ/ДА',
                'type' => 'select',
                'excel_cell' => 'D4',
                'tooltip' => 'Наличие горизонтальной гидроизоляции плиты перекрытия',
                'validation' => 'required',
                'order' => 1,
            ],
            [
                'form_type' => 'lp',
                'name' => 'blind',
                'label' => 'Отмосток НЕТ/ДА',
                'type' => 'select',
                'excel_cell' => 'D5',
                'tooltip' => 'Наличие отмостка',
                'validation' => 'required',
                'order' => 2,
            ],
            [
                'form_type' => 'lp',
                'name' => 'blindBase',
                'label' => 'Основание отмостка щебень/песок',
                'type' => 'select',
                'excel_cell' => 'D6',
                'tooltip' => 'Материал основания отмостка',
                'validation' => 'required',
                'order' => 3,
            ],
            [
                'form_type' => 'lp',
                'name' => 'blindWidth',
                'label' => 'Ширина отмостка (м)',
                'type' => 'number',
                'excel_cell' => 'D7',
                'tooltip' => 'Ширина отмостка (не более 1,2 м)',
                'validation' => 'required|numeric|min:0|max:1.2',
                'order' => 4,
            ],
            [
                'form_type' => 'lp',
                'name' => 'slabThickness',
                'label' => 'Толщина плиты перекрытия (м)',
                'type' => 'number',
                'excel_cell' => 'D8',
                'tooltip' => 'Толщина плиты перекрытия',
                'validation' => 'required|numeric|min:0',
                'order' => 5,
            ],
            [
                'form_type' => 'lp',
                'name' => 'slabArea',
                'label' => 'Площадь плиты перекрытия (м2)',
                'type' => 'number',
                'excel_cell' => 'D9',
                'tooltip' => 'Площадь плиты перекрытия',
                'validation' => 'required|numeric|min:0',
                'order' => 6,
            ],
            [
                'form_type' => 'lp',
                'name' => 'outerLength',
                'label' => 'Длина ленты внешней (по внешнему габариту) (м)',
                'type' => 'number',
                'excel_cell' => 'D10',
                'tooltip' => 'Длина ленты внешней по внешнему габариту',
                'validation' => 'required|numeric|min:0',
                'order' => 7,
            ],
            [
                'form_type' => 'lp',
                'name' => 'outerWidth',
                'label' => 'Ширина ленты внешней (м)',
                'type' => 'number',
                'excel_cell' => 'D11',
                'tooltip' => 'Ширина ленты внешней',
                'validation' => 'required|numeric|min:0',
                'order' => 8,
            ],
            [
                'form_type' => 'lp',
                'name' => 'innerLength',
                'label' => 'Длина ленты внутренней (м)',
                'type' => 'number',
                'excel_cell' => 'D12',
                'tooltip' => 'Длина ленты внутренней',
                'validation' => 'required|numeric|min:0',
                'order' => 9,
            ],
            [
                'form_type' => 'lp',
                'name' => 'innerWidth',
                'label' => 'Ширина ленты внутренней (м)',
                'type' => 'number',
                'excel_cell' => 'D13',
                'tooltip' => 'Ширина ленты внутренней',
                'validation' => 'required|numeric|min:0',
                'order' => 10,
            ],
            [
                'form_type' => 'lp',
                'name' => 'plinthHeight',
                'label' => 'Высота цоколя (от верх. точки грунта) (м)',
                'type' => 'number',
                'excel_cell' => 'D14',
                'tooltip' => 'Высота цоколя от верхней точки грунта',
                'validation' => 'required|numeric|min:0',
                'order' => 11,
            ],
            [
                'form_type' => 'lp',
                'name' => 'crossIntersections',
                'label' => 'Количество пересечений крест (шт)',
                'type' => 'number',
                'excel_cell' => 'D15',
                'tooltip' => 'Количество пересечений крест',
                'validation' => 'required|integer|min:0',
                'order' => 12,
            ],
            [
                'form_type' => 'lp',
                'name' => 'tIntersections',
                'label' => 'Количество пересечений Т-обр (шт)',
                'type' => 'number',
                'excel_cell' => 'D16',
                'tooltip' => 'Количество пересечений Т-образных',
                'validation' => 'required|integer|min:0',
                'order' => 13,
            ],
            [
                'form_type' => 'lp',
                'name' => 'cornerCount90',
                'label' => 'Количество углов 90 гр (шт)',
                'type' => 'number',
                'excel_cell' => 'D17',
                'tooltip' => 'Количество углов 90 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 14,
            ],
            [
                'form_type' => 'lp',
                'name' => 'cornerCount45',
                'label' => 'Количество углов 45 гр (шт)',
                'type' => 'number',
                'excel_cell' => 'D18',
                'tooltip' => 'Количество углов 45 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 15,
            ],
            [
                'form_type' => 'lp',
                'name' => 'innerCornerCount',
                'label' => 'Количество внутренних углов при отмостке (шт)',
                'type' => 'number',
                'excel_cell' => 'D19',
                'tooltip' => 'Количество внутренних углов при отмостке',
                'validation' => 'required|integer|min:0',
                'order' => 16,
            ],
            [
                'form_type' => 'lp',
                'name' => 'buildingAreaOverlap',
                'label' => 'Перепад по пятну застройки (м)',
                'type' => 'number',
                'excel_cell' => 'D20',
                'tooltip' => 'Перепад по пятну застройки',
                'validation' => 'required|numeric|min:0',
                'order' => 17,
            ],
            [
                'form_type' => 'lp',
                'name' => 'sandBaseThickness',
                'label' => 'Толщина песчаного основания (м)',
                'type' => 'number',
                'excel_cell' => 'D21',
                'tooltip' => 'Толщина песчаного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 18,
            ],
            [
                'form_type' => 'lp',
                'name' => 'crushedStoneBaseThickness',
                'label' => 'Толщина щебеночного основания (м)',
                'type' => 'number',
                'excel_cell' => 'D22',
                'tooltip' => 'Толщина щебеночного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 19,
            ],
            [
                'form_type' => 'lp',
                'name' => 'buildingAreaSize',
                'label' => 'S пятна застройки (м2)',
                'type' => 'number',
                'excel_cell' => 'D23',
                'tooltip' => 'Площадь пятна застройки',
                'validation' => 'required|numeric|min:0',
                'order' => 20,
            ],
            // MP (Монолитная Плита) form fields
            [
                'form_type' => 'mp',
                'name' => 'buildingType',
                'label' => 'Вид строения дерево/камень 1/0',
                'type' => 'select',
                'excel_cell' => 'D1',
                'tooltip' => 'Выберите тип строения: дерево или камень',
                'validation' => 'required',
                'order' => 1,
            ],
            [
                'form_type' => 'mp',
                'name' => 'blindInsulationWidth',
                'label' => 'Ширина утепления под отмосток',
                'type' => 'number',
                'excel_cell' => 'D2',
                'tooltip' => 'Ширина утепления под отмосток (не более 1200 мм)',
                'validation' => 'required|numeric|min:0|max:1.2',
                'order' => 2,
            ],
            [
                'form_type' => 'mp',
                'name' => 'innerCornerCount',
                'label' => 'Количество внутренних углов от примыканий дополнительных плит',
                'type' => 'number',
                'excel_cell' => 'D3',
                'tooltip' => 'Количество внутренних углов от примыканий дополнительных плит',
                'validation' => 'required|integer|min:0',
                'order' => 3,
            ],
            [
                'form_type' => 'mp',
                'name' => 'mainFoundationArea',
                'label' => 'S плиты фундаментной основная',
                'type' => 'number',
                'excel_cell' => 'D4',
                'tooltip' => 'Площадь основной фундаментной плиты',
                'validation' => 'required|numeric|min:0',
                'order' => 4,
            ],
            [
                'form_type' => 'mp',
                'name' => 'mainFoundationPerimeter',
                'label' => 'Внешний периметр основной плиты',
                'type' => 'number',
                'excel_cell' => 'D5',
                'tooltip' => 'Внешний периметр основной фундаментной плиты',
                'validation' => 'required|numeric|min:0',
                'order' => 5,
            ],
            [
                'form_type' => 'mp',
                'name' => 'mainFoundationThickness',
                'label' => 'Толщина основной плиты',
                'type' => 'number',
                'excel_cell' => 'D6',
                'tooltip' => 'Толщина основной фундаментной плиты',
                'validation' => 'required|numeric|min:0',
                'order' => 6,
            ],
            [
                'form_type' => 'mp',
                'name' => 'reinforcementType',
                'label' => 'Ячейка арматуры 200х200/150х150 1/0',
                'type' => 'select',
                'excel_cell' => 'D7',
                'tooltip' => 'Выберите тип армирования: 200х200 или 150х150',
                'validation' => 'required',
                'order' => 7,
            ],
            [
                'form_type' => 'mp',
                'name' => 'corner90Count',
                'label' => 'Количество углов 90 гр',
                'type' => 'number',
                'excel_cell' => 'D8',
                'tooltip' => 'Количество углов 90 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 8,
            ],
            [
                'form_type' => 'mp',
                'name' => 'corner45Count',
                'label' => 'Количество углов 45 гр',
                'type' => 'number',
                'excel_cell' => 'D9',
                'tooltip' => 'Количество углов 45 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 9,
            ],
            [
                'form_type' => 'mp',
                'name' => 'groundLevelDifference',
                'label' => 'Глубина заложения (низ плиты от уровня грунта)',
                'type' => 'number',
                'excel_cell' => 'D10',
                'tooltip' => 'Глубина заложения плиты от уровня грунта',
                'validation' => 'required|numeric|min:0',
                'order' => 10,
            ],
            // ... (Additional fields for Доп плита №1, №2, №3, Проём №1, №2, №3)
            [
                'form_type' => 'mp',
                'name' => 'buildingAreaOverlap',
                'label' => 'Перепад по пятну застройки',
                'type' => 'number',
                'excel_cell' => 'D68',
                'tooltip' => 'Перепад по пятну застройки',
                'validation' => 'required|numeric|min:0',
                'order' => 68,
            ],
            [
                'form_type' => 'mp',
                'name' => 'sandBaseThickness',
                'label' => 'Толщина песчаного основания',
                'type' => 'number',
                'excel_cell' => 'D69',
                'tooltip' => 'Толщина песчаного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 69,
            ],
            [
                'form_type' => 'mp',
                'name' => 'crushedStoneBaseThickness',
                'label' => 'Толщина щебеночного основания',
                'type' => 'number',
                'excel_cell' => 'D70',
                'tooltip' => 'Толщина щебеночного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 70,
            ],
            [
                'form_type' => 'mp',
                'name' => 'concreteBaseThickness',
                'label' => 'Толщина подбетонного основания',
                'type' => 'number',
                'excel_cell' => 'D71',
                'tooltip' => 'Толщина подбетонного основания',
                'validation' => 'required|numeric|min:0',
                'order' => 71,
            ],
            [
                'form_type' => 'mp',
                'name' => 'insulationThickness',
                'label' => 'Толщина утепления (ЭППС) 0,05/0,1',
                'type' => 'select',
                'excel_cell' => 'D72',
                'tooltip' => 'Выберите толщину утепления: 0,05 или 0,1',
                'validation' => 'required',
                'order' => 72,
            ],
            [
                'form_type' => 'mp',
                'name' => 'concreteWaterproofing',
                'label' => 'Подбетонка гидроизоляция да/нет 1/0',
                'type' => 'select',
                'excel_cell' => 'D73',
                'tooltip' => 'Наличие гидроизоляции подбетонки',
                'validation' => 'required',
                'order' => 73,
            ],
            [
                'form_type' => 'mp',
                'name' => 'waterSupplyLength',
                'label' => 'Ввод ХВС длина от точки до края ф-та',
                'type' => 'number',
                'excel_cell' => 'D74',
                'tooltip' => 'Длина ввода холодного водоснабжения',
                'validation' => 'required|numeric|min:0',
                'order' => 74,
            ],
            [
                'form_type' => 'mp',
                'name' => 'sewerageLength',
                'label' => 'Ввод ЗСМ длина от точки до края ф-та',
                'type' => 'number',
                'excel_cell' => 'D75',
                'tooltip' => 'Длина ввода канализации',
                'validation' => 'required|numeric|min:0',
                'order' => 75,
            ],
            [
                'form_type' => 'mp',
                'name' => 'electricityLength',
                'label' => 'Ввод СС длина от точки до края ф-та',
                'type' => 'number',
                'excel_cell' => 'D76',
                'tooltip' => 'Длина ввода электричества',
                'validation' => 'required|numeric|min:0',
                'order' => 76,
            ],
            [
                'form_type' => 'mp',
                'name' => 'sewagePoint1Length',
                'label' => 'Вывод канализации точка 1 длина до точки',
                'type' => 'number',
                'excel_cell' => 'D77',
                'tooltip' => 'Длина вывода канализации до точки 1',
                'validation' => 'required|numeric|min:0',
                'order' => 77,
            ],
            [
                'form_type' => 'mp',
                'name' => 'sewagePoint2Length',
                'label' => 'Вывод канализации точка 2 длина до точки',
                'type' => 'number',
                'excel_cell' => 'D78',
                'tooltip' => 'Длина вывода канализации до точки 2',
                'validation' => 'required|numeric|min:0',
                'order' => 78,
            ],
            [
                'form_type' => 'mp',
                'name' => 'sewagePoint3Length',
                'label' => 'Вывод канализации точка 3 длина до точки',
                'type' => 'number',
                'excel_cell' => 'D79',
                'tooltip' => 'Длина вывода канализации до точки 3',
                'validation' => 'required|numeric|min:0',
                'order' => 79,
            ],
            [
                'form_type' => 'mp',
                'name' => 'objectRemoteness',
                'label' => 'Удаленность объекта от МКАД',
                'type' => 'number',
                'excel_cell' => 'D80',
                'tooltip' => 'Удаленность объекта от МКАД в километрах',
                'validation' => 'required|numeric|min:0',
                'order' => 80,
            ],
            [
                'form_type' => 'mp',
                'name' => 'blind',
                'label' => 'Отмосток да/нет 1/0',
                'type' => 'select',
                'excel_cell' => 'D81',
                'tooltip' => 'Наличие отмостки',
                'validation' => 'required',
                'order' => 81,
            ],
            [
                'form_type' => 'mp',
                'name' => 'blindPerimeter',
                'label' => 'По периметру плит/ по габариту общему с учетом лент',
                'type' => 'select',
                'excel_cell' => 'D82',
                'tooltip' => 'Выберите тип периметра для отмостки',
                'validation' => 'required',
                'order' => 82,
            ],
            [
                'form_type' => 'mp',
                'name' => 'blindLength',
                'label' => 'Габаритная длина отмостка лент',
                'type' => 'number',
                'excel_cell' => 'D83',
                'tooltip' => 'Габаритная длина отмостки лент',
                'validation' => 'required|numeric|min:0',
                'order' => 83,
            ],
            [
                'form_type' => 'mp',
                'name' => 'outerCornerCount',
                'label' => 'Количество внешних углов',
                'type' => 'number',
                'excel_cell' => 'D84',
                'tooltip' => 'Количество внешних углов',
                'validation' => 'required|integer|min:0',
                'order' => 84,
            ],
            [
                'form_type' => 'mp',
                'name' => 'innerCornerCount',
                'label' => 'Количество внутренних углов',
                'type' => 'number',
                'excel_cell' => 'D85',
                'tooltip' => 'Количество внутренних углов',
                'validation' => 'required|integer|min:0',
                'order' => 85,
            ],
            [
                'form_type' => 'mp',
                'name' => 'stripAdjacencyLength',
                'label' => 'Длина между точками примыкания лент к плите',
                'type' => 'number',
                'excel_cell' => 'D86',
                'tooltip' => 'Длина между точками примыкания лент к плите',
                'validation' => 'required|numeric|min:0',
                'order' => 86,
            ],
            [
                'form_type' => 'mp',
                'name' => 'foundationThickness',
                'label' => 'Толщина основания',
                'type' => 'number',
                'excel_cell' => 'D87',
                'tooltip' => 'Толщина основания',
                'validation' => 'required|numeric|min:0',
                'order' => 87,
            ],
            [
                'form_type' => 'mp',
                'name' => 'foundationBase',
                'label' => 'Основание песок/щебень',
                'type' => 'select',
                'excel_cell' => 'D88',
                'tooltip' => 'Выберите тип основания: песок или щебень',
                'validation' => 'required',
                'order' => 88,
            ],
            // SRP (Ленточный армированный фундамент) form fields
            [
                'form_type' => 'srp',
                'name' => 'horizontalWaterproofing',
                'label' => 'Горизонтальная гидроизоляция плиты перекрытия НЕТ/ДА',
                'type' => 'select',
                'excel_cell' => 'D4',
                'tooltip' => 'Наличие горизонтальной гидроизоляции плиты перекрытия',
                'validation' => 'required',
                'order' => 1,
            ],
            [
                'form_type' => 'srp',
                'name' => 'blind',
                'label' => 'Отмосток НЕТ/ДА',
                'type' => 'select',
                'excel_cell' => 'D5',
                'tooltip' => 'Наличие отмостки',
                'validation' => 'required',
                'order' => 2,
            ],
            [
                'form_type' => 'srp',
                'name' => 'blindBase',
                'label' => 'Основание отмостка щебень/песок',
                'type' => 'select',
                'excel_cell' => 'D6',
                'tooltip' => 'Материал основания отмостки',
                'validation' => 'required',
                'order' => 3,
            ],
            [
                'form_type' => 'srp',
                'name' => 'blindWidth',
                'label' => 'Ширина отмостка',
                'type' => 'number',
                'excel_cell' => 'D7',
                'tooltip' => 'Ширина отмостки в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 4,
            ],
            [
                'form_type' => 'srp',
                'name' => 'slabThickness',
                'label' => 'Толщина плиты перекрытия',
                'type' => 'number',
                'excel_cell' => 'D8',
                'tooltip' => 'Толщина плиты перекрытия в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 5,
            ],
            [
                'form_type' => 'srp',
                'name' => 'slabArea',
                'label' => 'Площадь плиты перекрытия',
                'type' => 'number',
                'excel_cell' => 'D9',
                'tooltip' => 'Площадь плиты перекрытия в квадратных метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 6,
            ],
            [
                'form_type' => 'srp',
                'name' => 'outerLength',
                'label' => 'Длина ленты внешней (по внешнему габариту)',
                'type' => 'number',
                'excel_cell' => 'D10',
                'tooltip' => 'Длина внешней ленты по внешнему габариту в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 7,
            ],
            [
                'form_type' => 'srp',
                'name' => 'outerWidth',
                'label' => 'Ширина ленты внешней',
                'type' => 'number',
                'excel_cell' => 'D11',
                'tooltip' => 'Ширина внешней ленты в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 8,
            ],
            [
                'form_type' => 'srp',
                'name' => 'innerLength',
                'label' => 'Длина ленты внутренней',
                'type' => 'number',
                'excel_cell' => 'D12',
                'tooltip' => 'Длина внутренней ленты в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 9,
            ],
            [
                'form_type' => 'srp',
                'name' => 'innerWidth',
                'label' => 'Ширина ленты внутренней',
                'type' => 'number',
                'excel_cell' => 'D13',
                'tooltip' => 'Ширина внутренней ленты в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 10,
            ],
            [
                'form_type' => 'srp',
                'name' => 'plinthHeight',
                'label' => 'Высота цоколя (от верх. точки грунта)',
                'type' => 'number',
                'excel_cell' => 'D14',
                'tooltip' => 'Высота цоколя от верхней точки грунта в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 11,
            ],
            [
                'form_type' => 'srp',
                'name' => 'crossIntersections',
                'label' => 'Количество пересечений крест',
                'type' => 'number',
                'excel_cell' => 'D15',
                'tooltip' => 'Количество крестообразных пересечений',
                'validation' => 'required|integer|min:0',
                'order' => 12,
            ],
            [
                'form_type' => 'srp',
                'name' => 'tIntersections',
                'label' => 'Количество пересечений Т-обр',
                'type' => 'number',
                'excel_cell' => 'D16',
                'tooltip' => 'Количество Т-образных пересечений',
                'validation' => 'required|integer|min:0',
                'order' => 13,
            ],
            [
                'form_type' => 'srp',
                'name' => 'cornerCount90',
                'label' => 'Количество углов 90 гр',
                'type' => 'number',
                'excel_cell' => 'D17',
                'tooltip' => 'Количество углов 90 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 14,
            ],
            [
                'form_type' => 'srp',
                'name' => 'cornerCount45',
                'label' => 'Количество углов 45 гр',
                'type' => 'number',
                'excel_cell' => 'D18',
                'tooltip' => 'Количество углов 45 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 15,
            ],
            [
                'form_type' => 'srp',
                'name' => 'innerCornerCount',
                'label' => 'Количество внутренних углов при отмостке',
                'type' => 'number',
                'excel_cell' => 'D19',
                'tooltip' => 'Количество внутренних углов при отмостке',
                'validation' => 'required|integer|min:0',
                'order' => 16,
            ],
            [
                'form_type' => 'srp',
                'name' => 'buildingAreaOverlap',
                'label' => 'Перепад по пятну застройки',
                'type' => 'number',
                'excel_cell' => 'D20',
                'tooltip' => 'Перепад по пятну застройки в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 17,
            ],
            [
                'form_type' => 'srp',
                'name' => 'sandBaseThickness',
                'label' => 'Толщина песчаного основания',
                'type' => 'number',
                'excel_cell' => 'D21',
                'tooltip' => 'Толщина песчаного основания в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 18,
            ],
            [
                'form_type' => 'srp',
                'name' => 'crushedStoneBaseThickness',
                'label' => 'Толщина щебеночного основания',
                'type' => 'number',
                'excel_cell' => 'D22',
                'tooltip' => 'Толщина щебеночного основания в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 19,
            ],
            [
                'form_type' => 'srp',
                'name' => 'buildingAreaSize',
                'label' => 'S пятна застройки',
                'type' => 'number',
                'excel_cell' => 'D23',
                'tooltip' => 'Площадь пятна застройки в квадратных метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 20,
            ],
            // SR (Ленточный фундамент) form fields
            [
                'form_type' => 'sr',
                'name' => 'outerLength',
                'label' => 'Длина ленты внешней (по внешнему габариту)',
                'type' => 'number',
                'excel_cell' => 'D4',
                'tooltip' => 'Длина внешней ленты по внешнему габариту в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 1,
            ],
            [
                'form_type' => 'sr',
                'name' => 'outerWidth',
                'label' => 'Ширина ленты внешней',
                'type' => 'number',
                'excel_cell' => 'D5',
                'tooltip' => 'Ширина внешней ленты в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 2,
            ],
            [
                'form_type' => 'sr',
                'name' => 'innerLength',
                'label' => 'Длина ленты внутренней',
                'type' => 'number',
                'excel_cell' => 'D6',
                'tooltip' => 'Длина внутренней ленты в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 3,
            ],
            [
                'form_type' => 'sr',
                'name' => 'innerWidth',
                'label' => 'Ширина ленты внутренней',
                'type' => 'number',
                'excel_cell' => 'D7',
                'tooltip' => 'Ширина внутренней ленты в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 4,
            ],
            [
                'form_type' => 'sr',
                'name' => 'plinthHeight',
                'label' => 'Высота цоколя (от верх. точки грунта)',
                'type' => 'number',
                'excel_cell' => 'D8',
                'tooltip' => 'Высота цоколя от верхней точки грунта в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 5,
            ],
            [
                'form_type' => 'sr',
                'name' => 'crossIntersections',
                'label' => 'Количество пересечений крест',
                'type' => 'number',
                'excel_cell' => 'D9',
                'tooltip' => 'Количество крестообразных пересечений',
                'validation' => 'required|integer|min:0',
                'order' => 6,
            ],
            [
                'form_type' => 'sr',
                'name' => 'tIntersections',
                'label' => 'Количество пересечений Т-обр',
                'type' => 'number',
                'excel_cell' => 'D10',
                'tooltip' => 'Количество Т-образных пересечений',
                'validation' => 'required|integer|min:0',
                'order' => 7,
            ],
            [
                'form_type' => 'sr',
                'name' => 'cornerCount90',
                'label' => 'Количество углов 90 гр',
                'type' => 'number',
                'excel_cell' => 'D11',
                'tooltip' => 'Количество углов 90 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 8,
            ],
            [
                'form_type' => 'sr',
                'name' => 'cornerCount45',
                'label' => 'Количество углов 45 гр',
                'type' => 'number',
                'excel_cell' => 'D12',
                'tooltip' => 'Количество углов 45 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 9,
            ],
            [
                'form_type' => 'sr',
                'name' => 'buildingAreaOverlap',
                'label' => 'Перепад по пятну застройки',
                'type' => 'number',
                'excel_cell' => 'D13',
                'tooltip' => 'Перепад по пятну застройки в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 10,
            ],
            [
                'form_type' => 'sr',
                'name' => 'sandBaseThickness',
                'label' => 'Толщина песчаного основания',
                'type' => 'number',
                'excel_cell' => 'D14',
                'tooltip' => 'Толщина песчаного основания в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 11,
            ],
            [
                'form_type' => 'sr',
                'name' => 'crushedStoneBaseThickness',
                'label' => 'Толщина щебеночного основания',
                'type' => 'number',
                'excel_cell' => 'D15',
                'tooltip' => 'Толщина щебеночного основания в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 12,
            ],
            [
                'form_type' => 'sr',
                'name' => 'buildingAreaSize',
                'label' => 'S пятна застройки',
                'type' => 'number',
                'excel_cell' => 'D16',
                'tooltip' => 'Площадь пятна застройки в квадратных метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 13,
            ],
            [
                'form_type' => 'sr',
                'name' => 'stripLength',
                'label' => 'Длина сваи',
                'type' => 'number',
                'excel_cell' => 'D17',
                'tooltip' => 'Длина сваи в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 14,
            ],
            [
                'form_type' => 'srp',
                'name' => 'tIntersections',
                'label' => 'Количество пересечений Т-обр',
                'type' => 'number',
                'excel_cell' => 'D16',
                'tooltip' => 'Количество Т-образных пересечений',
                'validation' => 'required|integer|min:0',
                'order' => 13,
            ],
            [
                'form_type' => 'srp',
                'name' => 'cornerCount90',
                'label' => 'Количество углов 90 гр',
                'type' => 'number',
                'excel_cell' => 'D17',
                'tooltip' => 'Количество углов 90 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 14,
            ],
            [
                'form_type' => 'srp',
                'name' => 'cornerCount45',
                'label' => 'Количество углов 45 гр',
                'type' => 'number',
                'excel_cell' => 'D18',
                'tooltip' => 'Количество углов 45 градусов',
                'validation' => 'required|integer|min:0',
                'order' => 15,
            ],
            [
                'form_type' => 'srp',
                'name' => 'innerCornerCount',
                'label' => 'Количество внутренних углов при отмостке',
                'type' => 'number',
                'excel_cell' => 'D19',
                'tooltip' => 'Количество внутренних углов при отмостке',
                'validation' => 'required|integer|min:0',
                'order' => 16,
            ],
            [
                'form_type' => 'srp',
                'name' => 'buildingAreaOverlap',
                'label' => 'Перепад по пятну застройки',
                'type' => 'number',
                'excel_cell' => 'D20',
                'tooltip' => 'Перепад по пятну застройки в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 17,
            ],
            [
                'form_type' => 'srp',
                'name' => 'sandBaseThickness',
                'label' => 'Толщина песчаного основания',
                'type' => 'number',
                'excel_cell' => 'D21',
                'tooltip' => 'Толщина песчаного основания в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 18,
            ],
            [
                'form_type' => 'srp',
                'name' => 'crushedStoneBaseThickness',
                'label' => 'Толщина щебеночного основания',
                'type' => 'number',
                'excel_cell' => 'D22',
                'tooltip' => 'Толщина щебеночного основания в метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 19,
            ],
            [
                'form_type' => 'srp',
                'name' => 'buildingAreaSize',
                'label' => 'S пятна застройки',
                'type' => 'number',
                'excel_cell' => 'D23',
                'tooltip' => 'Площадь пятна застройки в квадратных метрах',
                'validation' => 'required|numeric|min:0',
                'order' => 20,
            ],
        ];

        foreach ($fields as $field) {
            FormField::create($field);
        }
    }
}